<?php
namespace App\Controller;
use App\Entity\Produit;
use App\Entity\PhotoProduit;
use App\Form\ProduitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Routing\Annotation\Route; //add this line to add usage of Route class.
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class PhotoProduitController extends Controller
{
	

	public function addPhoto(Request $request)
	{
		$photo = new PhotoProduit();
		$form   = $this->get('form.factory')->create(ProduitType::class, $photo);

		if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
		  $file = $photo->getPhoto();
		  $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
		  $file->move(
                $this->getParameter('photoProduit_directory'),
                $fileName
            );
		  $photo->setPhoto($fileName);
		  $em = $this->getDoctrine()->getManager();
		  $em->persist($photo);
		  $em->flush();
	}
	}
	
	private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
	
}